const data = {
    products: [

        {
            _id: '1',
            name: 'First Model',
            category: 'sofa',
            image: '/images/product-1.jpg',
            price: 120,
            brand: 'Divan',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Second Model',
            category: ' bench',
            image: '/images/product-2.jpg',
            price: 140,
            brand: 'tv bench',
            rating: 4.3,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Third Model',
            category: 'sofa',
            image: '/images/product-3.jpg',
            price: 160,
            brand: 'leather sofa',
            rating: 4.8,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Fourth Model',
            category: 'sofa',
            image: '/images/product-4.jpg',
            price: 180,
            brand: 'classic',
            rating: 4.2,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Fifth Model',
            category: 'table',
            image: '/images/product-5.jpg',
            price: 200,
            brand: 'kitchen table',
            rating: 4.5,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'sixth Model',
            category: 'bed',
            image: '/images/product-6.jpg',
            price: 220,
            brand: 'baby bed',
            rating: 4.9,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;